### Register a new contract
POST https://localhost:7195/api/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### Login
POST https://localhost:7195/api/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password123"
}

### Create a new contract
POST https://localhost:7195/api/contract
Content-Type: application/json

{
  "contractName": "New Contract",
  "startDate": "2024-08-01T00:00:00Z",
  "endDate": "2025-08-01T00:00:00Z",
  "title": "Sample Title",
  "content": "Sample Content"
}

### Get contract by ID
GET https://localhost:7195/api/contract/1
Accept: application/json